### ISSUE TITLE
Description of transformCursor does not match the implementation

### ISSUE THREAD

**Issue by gkubisa** [ottypes/docs#25]
As I see, only https://github.com/ottypes/json0 and https://github.com/ottypes/rich-text implement `transformCursor` and both use the `isOwnOp` param to decide whether an "insert" action *at* the cursor position should push the cursor forward or not. However, the docs say "If isOwnOp is true, this function should return the final editing position of the provided operation.", which does not match the current implementations.

IMHO, the implemented behaviour makes more sense (consistent with `transform` - the last param is for breaking ties rather than completely changing the behaviour of the function), so the docs should be updated.

See also:

- https://github.com/quilljs/delta/blob/7bd06c62b768f1a045acd41e785a83f35d4b0e94/lib/delta.js#L305
- https://github.com/ottypes/json0/blob/8974b416c815df79428c86101ca4e3eeade1d8db/lib/text0.js#L166-L171

**Comment by josephg** [comment]
Yeah this sounds right. Feel like putting in a PR to update the documentation?
