### ISSUE TITLE
Please, explain the build process

### ISSUE THREAD

**Issue by antonyc** [ottypes/docs#8]
I am ok with reading makefiles, but there obviously are two of them to run manually, in ottypes and then in sharejs.
So, please create a short manual of how to build the JS for client.

**Comment by curran** [comment]
This feels closeable due to inactivity.

**Comment by chaporgin** [comment]
Totally.

**Comment by josephg** [comment]
And, for an explanation: There is no "JS for client" here. This repository is only a specification. And other repositories (eg text-unicode) also aren't OT clients.

**Comment by curran** [comment]
And, for additional reference, here are some example builds:
 * https://github.com/share/sharedb/tree/master/examples - Browserify (sort of a dated approach)
 * https://github.com/curran/sharedb-client-browser - Rollup
